### ISSUE TITLE
Missing templates in sensorml2iso conda package from conda-forge

### ISSUE THREAD

**Issue by lsetiawan** [ioos/sensorml2iso#17]
Hi! 

I installed `sensorml2iso` from  conda-forge into a new conda environment, then trying to run it, I get a `TemplateNotFound` error:

```bash
$ sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp --output_dir $ISOPATH
Success, no errors returned from DescribeSensor requests in service: http://data.nanoos.org/52nsos/sos/kvp?acceptVersions=1.0.0&request=GetCapabilities&service=SOS
Traceback (most recent call last):
  File "/home/lsetiawan/miniconda/envs/test/bin/sensorml2iso", line 6, in <module>
    sys.exit(sensorml2iso.command_line.main())
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/command_line.py", line 98, in main
    obj.run()
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 171, in run
    self.generate_iso(stations_df)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/sensorml2iso.py", line 485, in generate_iso
    template = env.get_template('sensorml_iso.xml')
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sensorml_iso.xml
```

I went to `/home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso` and `sensorml_iso.xml` is indeed nowhere to be found. 

```bash
$ ls /home/lsetiawan/miniconda/envs/test/lib/python2.7/site-packages/sensorml2iso/
command_line.py  command_line.pyc  __init__.py  __init__.pyc  sensorml2iso.py  sensorml2iso.pyc
```

Looking at the [main repo](https://github.com/ioos/sensorml2iso/tree/master/sensorml2iso) of this package, it seems like the `templates` folder did not get included in the conda package. 

CC. @ocefpaf @emiliom

**Comment by ocefpaf** [comment]
Looking into it now. It seems that the `templates` directory does exist in the tarball used to package, so it is a packaging bug on `conda-forge` side.

**Comment by ocefpaf** [comment]
Spoke too soon. The problem is in the original code. #18 should fix it. I will patch the `conda-forge` package and bump the build number so we don't have to wait for a new release.

**Comment by lsetiawan** [comment]
Linking issue for reference of what we are trying to do: https://github.com/nanoos-pnw/ioos-ws/issues/9
